resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: External-CI-Token
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - 'CHANGELOG.md'
    - 'CODEOWNERS'
    - 'copyright'
    - 'README.txt'

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - 'CHANGELOG.md'
    - 'CODEOWNERS'
    - 'copyright'
    - 'README.txt'
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocm-core.yml@pipelines_repo
